let div = document. getElementById ("div1");
div.style.height = "200px"
div.style.width = "300px"
div.style.padding = "10px";
div.style.margin = "20px";
div.style.fontSize = "18px";
div.style.fontWeight = "bold";
div.style.color = "rgb(0,0,255)"
div.style.backgroundColor = "Yellow"
